Repository training-bot/labs11-trainingBot-FE, pull requests merged in 2019-04, with the labels that each got.

#62 Dashboard routing refactor
  client/src/components/AppBar/AppBar.js
  client/src/components/Dashboard/DashboardView.js
  client/src/components/LandingPage/LandingPageView.js
  client/src/components/Modals/TeamMemberModal.js
  client/src/components/Modals/addToTrainingSeriesModal.js
  client/src/components/Modals/deleteModal.js
  client/src/components/Profile/ProfileView.js
  client/src/components/TeamMembers/TeamMemberMenuBtn.js
  client/src/components/TeamMembers/TeamMemberPage.js
  client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
  client/src/routes.js
  client/src/store/actions/teamMembersActions.js
  client/src/store/reducers/teamMembersReducer.js
  client/yarn.lock
Labels: Bug Fix, Feature Implemented

#63 Development
  client/package.json
  client/public/index.html
  client/src/components/AppBar/AppBar.js
  client/src/components/Dashboard/Dashboard.js
  client/src/components/Dashboard/DashboardView.js
  client/src/components/LandingPage/LandingPageView.js
  client/src/components/Modals/PostModal.js
  client/src/components/Modals/PostOptionsModal.js
  client/src/components/Modals/SlideDownModal.js
  client/src/components/Modals/TeamMemberModal.js
  client/src/components/Modals/TrainingSeriesModal.js
  client/src/components/Modals/addToTrainingSeriesModal.js
  client/src/components/Modals/deleteModal.js
  client/src/components/Modals/userModal.js
  client/src/components/Profile/Profile.js
  client/src/components/Profile/ProfileView.js
  client/src/components/Progress/ProgressCircle.js
  client/src/components/Stripe/CheckoutForm.js
  client/src/components/Stripe/unsubscribeModal.js
  client/src/components/TeamMembers/TeamMember.js
  client/src/components/TeamMembers/TeamMemberMenuBtn.js
  client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
  client/src/components/TeamMembers/TeamMembersList.js
  client/src/components/TeamMembers/TeamMembersView.js
  client/src/components/TrainingSeries/TrainingSeries.js
  client/src/components/TrainingSeries/TrainingSeriesAssignment.js
  client/src/components/TrainingSeries/TrainingSeriesList.js
  client/src/components/TrainingSeries/TrainingSeriesPosts.js
  client/src/components/TrainingSeries/TrainingSeriesSubView.js
  client/src/components/TrainingSeries/TrainingSeriesView.js
  client/src/img/trainingBot.gif
  client/src/routes.js
  client/src/store/actions/teamMembersActions.js
  client/src/store/actions/userActions.js
  client/src/store/reducers/teamMembersReducer.js
  client/src/store/reducers/userReducer.js
  client/yarn.lock
  node_modules/.yarn-integrity
  package.json
Labels: Bug Fix, Feature Implemented

#84 Trainingseries refactor
  client/src/components/Dashboard/DashboardView.js
  client/src/components/Modals/SlideDownModal.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMemberSnackbar.js
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
  client/src/components/TrainingSeries/TrainingSeriesPosts.js
Labels: Feature Implemented

#89 Filter assigned
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
Labels: enhancement

#92 Added search functionality to search posts on the training series page.
  client/src/components/TrainingSeries/TrainingSeriesPosts.js
Labels: enhancement

#94 Validate forms
  client/src/components/Dashboard/DashboardView.js
  client/src/components/Snackbar/Snackbar.js
  client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
  client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
  client/src/components/TrainingSeries/CreateTrainingSeries.js
  client/src/components/TrainingSeries/TrainingSeriesPosts.js
  client/src/store/reducers/userReducer.js
  client/yarn.lock
Labels: Bug Fix

#95 Fixed bug on first login crashing app
  client/src/components/Callback/callback.js
  client/src/components/Dashboard/DashboardView.js
  client/src/store/reducers/userReducer.js
Labels: Bug Fix

#111 Bug fix: Random snackbar
  client/src/components/Dashboard/DashboardView.js
Labels: Bug Fix

#121 Tutorial
  client/src/components/AppBar/AppBar.js
  client/src/components/Dashboard/DashboardView.js
  client/src/components/Notifications/NotificationsView.js
  client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
  client/src/components/TeamMembers/TeamMembersView.js
  client/src/components/Tour/DashboardTour.js
  client/src/components/TrainingSeries/CreateTrainingSeries.js
  client/src/components/TrainingSeries/TrainingSeriesSubView.js
  client/src/components/TrainingSeries/TrainingSeriesView.js
  client/src/store/reducers/userReducer.js
  node_modules/.yarn-integrity
  package.json
  yarn.lock
Labels: Feature Implemented

#138 Re-implemented tutorial into app
  client/src/components/AppBar/AppBar.js
  client/src/components/Callback/callback.js
  client/src/components/Dashboard/DashboardView.js
  client/src/components/Profile/ProfileView.js
  client/src/components/TeamMembers/TeamMembersView.js
  client/src/components/Tour/Tour.js
  client/src/components/TrainingSeries/TrainingSeriesSubView.js
  client/src/store/reducers/userReducer.js
Labels: Bug Fix

#152 Readme update
  Assets/Screenshot1.png
  Assets/Screenshot2.png
  Assets/Screenshot3.png
  Assets/Screenshot5.png
  Assets/Screenshot6.png
  Assets/screenshot4.png
  README.md
  client/src/components/LandingPage/LandingPageView.js
  client/src/components/LandingPage/Pricing.js
  client/src/components/LandingPage/Team.js
  client/src/index.css
  node_modules/.yarn-integrity
Labels: Bug Fix, enhancement
